# Generated by Django 3.2 on 2023-08-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytokens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='wallet_address',
        ),
    ]
